package dk.theknights.catapult.strategies.state;

/**
 * Created by Ole Gregersen (ole.gregersen@sallinggroup.com) on 3/8/18.
 */
public enum CatapultStateEnum {
	INITIAL,
	CATAPULT_TEMPLATE_NOT_FOUND,
	CATAPULT_TEMPLATE_FOUND,
	RELEASE_PROJECT_FOUND,
	RELEASE_PROJECT_NOT_FOUND,
	CATAPULT_TEMPLATE_CHANGED,
	OPENSHIFT_PROJECT_FOUND,
	OPENSHIFT_PROJECT_NOT_FOUND,
	OPENSHIFT_PROJECT_DELETED,
	CATAPULT_TEMPLATE_NOT_CHANGED,
	OPENSHIFT_PROJECT_CREATED,
	POLICY_BINDINGS_UPDATED,
	NO_SECRETS_FOUND,
	SECRETS_UPDATED,
	CONFIGMAPS_UPDATED,
	NO_CONFIGMAPS_FOUND,
	CATAPULT_TEMPLATE_PROCESSED,
	CATAPULT_TEMPLATE_PROCESS_ERROR,
	CATAPULT_DONE
}
